# Generated by Django 4.2.6 on 2025-03-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_linkedin', models.URLField(blank=True, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('total_funding_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('personal_contact', models.CharField(max_length=20)),
                ('personal_linkedin', models.URLField(blank=True, null=True)),
                ('company_work_email', models.EmailField(max_length=254, unique=True)),
                ('company_size', models.CharField(blank=True, max_length=20, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(max_length=100)),
                ('primary_business_model', models.CharField(blank=True, max_length=20, null=True)),
                ('funding_raised', models.CharField(default='no', max_length=3)),
                ('funding_rounds', models.IntegerField(blank=True, null=True)),
                ('latest_rounds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
