# Generated by Django 4.2.6 on 2025-03-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyregistration',
            old_name='user',
            new_name='user_id',
        ),
    ]
