# Generated by Django 4.2.6 on 2025-03-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_user_companyregistration_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='latest_rounds',
            field=models.CharField(blank=True, null=True),
        ),
    ]
