# Generated by Django 4.2.6 on 2025-03-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyregistration_latest_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyregistration',
            name='funding_raised',
        ),
    ]
