# Generated by Django 4.2.6 on 2025-04-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_companyregistration_funding_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='company_location',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
