# Generated by Django 4.2.6 on 2025-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyregistration_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='company_founder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
