# Generated by Django 4.2.6 on 2025-03-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentregistrationstatus',
            name='talent_status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
