# Generated by Django 4.2.6 on 2025-03-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpreferences',
            name='industry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpreferences',
            name='preferred_job_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='languageproficiency',
            name='proficiency_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='preferredworkterms',
            name='work_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='talentregistration',
            name='availability',
            field=models.CharField(default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='talentregistration',
            name='freelancer_status',
            field=models.CharField(default='full_time', max_length=20),
        ),
    ]
