# Generated by Django 4.2.6 on 2025-03-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('talent', '0002_talentregistrationstatus_talent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentregistrationstatus',
            name='user_id',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
