# Generated by Django 4.2.6 on 2025-03-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('talent', '0002_rename_certificate_image_skillsexpertise_certificate_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
