# Generated by Django 4.2.6 on 2025-03-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_alter_portfolioreferences_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioreferences',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
