# Generated by Django 4.2.6 on 2025-03-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_alter_quizresult_quiz_score_assignmentscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='AssignmentResult',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
