# Generated by Django 4.2.6 on 2025-03-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_skillsexpertise_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsexpertise',
            name='demo',
        ),
    ]
