# Generated by Django 4.2.6 on 2025-03-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_remove_skillsexpertise_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillsExpertise',
        ),
    ]
