# Generated by Django 4.2.6 on 2025-03-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('talent', '0010_delete_skillsexpertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_skills', models.JSONField(default=list)),
                ('secondary_skills', models.JSONField(blank=True, default=list, null=True)),
                ('certificate_images', models.JSONField(blank=True, default=list, null=True)),
                ('user_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
