# Generated by Django 4.2.6 on 2025-03-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_remove_quizresult_user_id_delete_assignmentresult_and_more'),
        ('talent', '0011_skillsexpertise'),
    ]

    operations = [
    ]
