# Generated by Django 4.2.6 on 2025-03-27 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('talent', '0012_merge_20250327_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_task', models.TextField(blank=True, null=True)),
                ('assignment_submission', models.TextField(blank=True, null=True)),
                ('assignment_score', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignmentScore',
        ),
    ]
