# Generated by Django 4.2.6 on 2025-03-30 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('talent', '0014_rename_user_assignmentresult_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentscore',
            name='work_score',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('interview_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_done', models.BooleanField(default=False)),
                ('interview_scheduled', models.DateTimeField(blank=True, null=True)),
                ('interview_score', models.CharField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
