# Generated by Django 4.2.6 on 2025-05-21 06:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emailotp'),
        ('talent', '0015_alter_talentscore_work_score_interviewresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpreferences',
            name='career_objective',
        ),
        migrations.RemoveField(
            model_name='jobpreferences',
            name='desired_role',
        ),
        migrations.RemoveField(
            model_name='jobpreferences',
            name='preferred_job_type',
        ),
        migrations.AddField(
            model_name='jobpreferences',
            name='frameworks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('interview_questions_id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.JSONField(default=list, help_text='List of 10 interview questions in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when questions were generated')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('interview_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_answers', models.JSONField(default=list, help_text='List of question-answer pairs with evaluation in JSON format')),
                ('score', models.FloatField(blank=True, help_text='Evaluation score out of 100', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when answers were submitted')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_answers', to='user_profile.userprofile')),
            ],
        ),
    ]
