# Generated by Django 4.2.6 on 2025-05-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emailotp'),
        ('talent', '0015_alter_talentscore_work_score_interviewresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('interview_questions_id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.JSONField(default=list, help_text='List of 10 interview questions in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when questions were generated')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('interview_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_answers', models.JSONField(default=list, help_text='List of question-answer pairs with evaluation in JSON format')),
                ('score', models.FloatField(blank=True, help_text='Evaluation score out of 100', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when answers were submitted')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_answers', to='user_profile.userprofile')),
            ],
        ),
    ]
