# Generated by Django 4.2.6 on 2025-05-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emailotp'),
        ('talent', '0016_remove_jobpreferences_career_objective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_task', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='user_profile.userprofile')),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
