# Generated by Django 4.2.6 on 2025-05-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0017_generatedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='cheating_suspected',
            field=models.BooleanField(default=False, help_text='Flag to indicate if cheating is suspected'),
        ),
    ]
