# Generated by Django 4.2.6 on 2025-05-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emailotp'),
        ('talent', '0018_interviewanswer_cheating_suspected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentscore',
            name='score_id',
        ),
        migrations.AlterField(
            model_name='talentscore',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_profile.userprofile'),
        ),
    ]
