# Generated by Django 4.2.6 on 2025-05-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emailotp'),
        ('talent', '0021_alter_talentscore_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', help_text='Current status of the interview', max_length=20)),
                ('scheduled_datetime', models.DateTimeField()),
                ('is_selected', models.BooleanField(default=False, help_text='Indicates if the talent is selected or not')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
    ]
