# Generated by Django 4.2.6 on 2025-06-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_emailotp'),
        ('talent', '0023_talentextrainfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user_id',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='jobpreferences',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='portfolioreferences',
            name='user_id',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='preferredworkterms',
            name='user_id',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='skillsexpertise',
            name='user_id',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='talentextrainfo',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='talentregistration',
            name='user_id',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
        ),
    ]
